name: Release
on:
  push:
    tags:
      - 'v[0-9]*.[0-9]*.[0-9]*'
jobs:
  release:
    runs-on: 'ubuntu-latest'
    steps:

    # Setup
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Configure Git
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
    - name: Install Helm
      uses: azure/setup-helm@v1
      with:
        version: v3.8.1

    # Gather Information
    # Check Versions
    - name: Check If Versions Match
      run: |
        cargo_version=$(cargo pkgid | cut -d'#' -f 2)
        helm_version=$(sed -n '/^version: / s/version: *// p' "charts/tplsrv/Chart.yaml")
        helm_appversion=$(sed -n '/^appVersion: / s/appVersion: *// p' "charts/tplsrv/Chart.yaml" | tr -d "\"'")

        set -x
        test "${cargo_version}"   = "${GITHUB_REF_NAME#v}"
        test "${helm_version}"    = "${GITHUB_REF_NAME#v}"
        test "${helm_appversion}" = "${GITHUB_REF_NAME}"

    # Upload Docker Image
    - name: Docker Meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: |
          withlazers/tplsrv
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: withlazers
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        context: .

    # Release Helm Chart
    - uses: withlazers/copy-to-repo-action@main
      with:
        ssh_key: ${{ secrets.HELMCHART_SSH_DEPLOY_KEY }}
        source_path: ./charts/tplsrv
        target_repository: withlazers/charts-withlazers
        target_path: ./charts/tplsrv
        commit_message: |
          automatic pipeline release of tplsrv ${{ github.ref_name }}

          Source: ${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}

    - uses: softprops/action-gh-release@v1
      with:
        generate_release_notes: true
        draft: true
